version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: mongo-db
  neo4j:
    environment:
      - NEO4J_AUTH=neo4j/twitter
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=["apoc"]
    image: neo4j:latest
    ports:
      - "7687:7687"
      - "7474:7474"
  twitter_stream_app:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - TWITTER_CONSUMER_KEY=${TWITTER_CONSUMER_KEY}
      - TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET}
      - TWITTER_BEARER_TOKEN=${TWITTER_BEARER_TOKEN}
    build:
      dockerfile:
        TwitterTest/Dockerfile
      context: ..
